### PR TITLE
Added Server sided validations for Posts

### PR DESCRIPTION
**Pull request by spandy1**
- Checking the uploaded media according to social platform's requirements.

### CODE REVIEW

**Comment by spandy1** [comment]
Making additional changes. Wait before merging.

**Comment by spandy1** [comment]
You can merge now.

**Comment by spandy1** [comment]
You can merge now.

**Review by jaydeepukani — COMMENTED** [review]
Update your branch with the main branch
Remove unknown files

**Comment by jaydeepukani** [comment]
Invalid PR so closing this PR

**Pull request closed without merging**
